Eliminate data races
open-rmf/rmf_ros2 pull request #129
Opened 2021-10-01 09:34 UTC by mxgrey

As reported in https://github.com/open-rmf/rmf_ros2/issues/82, Thread Sanitizer is complaining about many data races that are occurring in the `rmf_fleet_adapter` test code.

This PR combined with https://github.com/open-rmf/rmf_traffic/pull/46 should eliminate the vast majority (possibly all?) of them. After updating to these changes I have not seen a data race reported on the tests in a few dozen runs.

2021-10-01 18:20 UTC, mxgrey commented
Note that CI won't be able to pass until open-rmf/rmf_traffic#46 is merged.

2021-10-04 04:09 UTC, aaronchongth approved these changes
Thanks for tracking down the data races and fixing them! :bow: Just need to update the base branch, and we are good to go!

2021-10-04 05:13 UTC, aaronchongth commented
The failures seem to be coming from this possibly stale or incomplete test, https://github.com/open-rmf/rmf_ros2/blob/main/rmf_fleet_adapter/rmf_rxcpp/test/test_Transport.cpp#L104-L108 :thinking: And it looks like it was possibly to the section name clashing? I removed it and the data races were resolved.

2021-10-04 05:27 UTC, aaronchongth requested changes
Looks like the final failures are just linting issues, it seems to be complaining about these lines not indented, https://github.com/open-rmf/rmf_ros2/pull/129/files#diff-a5d4dd01175bb6932faad974abcee14d99fff47df3dc28e444ac5401594a951cR312-R333, as well as the bottom few suggestions I made

2021-10-04 05:27 UTC, aaronchongth commented on rmf_fleet_adapter/test/phases/test_GoToPlace.cpp
> +      [&](){ return pending_0->begin(); }));
```suggestion
      [&]() { return pending_0->begin(); }));
```

2021-10-04 05:27 UTC, aaronchongth commented on rmf_fleet_adapter/test/phases/test_GoToPlace.cpp
> +      [&](){ return pending_1->begin(); }));
```suggestion
      [&]() { return pending_1->begin(); }));
```

2021-10-04 07:32 UTC, mxgrey commented
@aaronchongth All checks are passing now. We just need a re-approval.

2021-10-04 07:45 UTC, aaronchongth approved these changes
LGTM!

2021-10-04 07:47 UTC, merged