Allow participants to sync up with remote databases when discrepancies arise
open-rmf/rmf_ros2 pull request #145
Opened 2021-12-01 16:57 UTC by mxgrey

There is a very small probability in the event of server restart race conditions that a participant may disagree with its remote database on details like its participant ID and description.

This PR allows participants to identify when these issues occur and work out a correction with the remote database.

We limit the rate at which these corrections can occur, because there is a risk of a pathological case where two participant instances believe they both own the same name. If that happens then they might viciously cycle against each other, each trying to "correct" the "bad" information that's being pushed by the other. In the worst case scenario that could be a very tight loop of hammering "corrective" messages at the schedule node. We limit the rate to 3 corrections per minute. Corrections happening at a higher rate than that should be brought to the attention of an operator.

To test this PR you can run four terminals with the following commands:
```
$  ros2 run rmf_traffic_ros2 changed_participant_schedule_node
```
```
$  ros2 run rmf_traffic_ros2 mock_repetitive_delay_participant
```
```
$ ros2 topic echo /rmf_traffic/itinerary_delay
```
```
$ ros2 topic echo /rmf_traffic/participants
```
Then watch as the participant makes corrections to the sabotage that the mocked up schedule node is causing. This scenario is also designed to demonstrate the rate limiting of the corrections.

2021-12-02 12:43 UTC, aaronchongth requested changes
This is looks amazing! Thanks for the explanation and comments along the way. I just have a few nitpicks, but in general I'm seeing the intended behavior and it should be in good shape to be merged after the base branch is updated.

2021-12-23 07:33 UTC, mxgrey commented on rmf_traffic_ros2/test/mock_schedule_nodes/missing_participant.cpp
> + * Copyright (C) 2020 Open Source Robotics Foundation
df59355

2021-12-23 07:33 UTC, mxgrey commented on rmf_traffic_ros2/test/mock_participants/repetitive_delay_participant.cpp
> + * Copyright (C) 2020 Open Source Robotics Foundation
df59355

2021-12-23 07:33 UTC, mxgrey commented on rmf_traffic_ros2/test/mock_schedule_nodes/missing_participant.cpp
> +        //std::dynamic_pointer_cast<DangerousDatabase>(database)->delete_participant(*this);
Deleted df59355

2021-12-23 08:49 UTC, aaronchongth approved these changes
Tests and demos are working fine, the example you provided with is working as expected too. Thanks!

2021-12-23 08:49 UTC, merged