Fix boost link problem
open-rmf/rmf_ros2 pull request #221
Opened 2022-08-16 04:17 UTC by orensbruli

2022-08-17 12:24 UTC, Yadunund requested changes
Minor comment to address. Also it looks like your commits are not GPG signed and hence DCO is failing.Once you've setup GPG you can 

```
git rebase -i -x "git commit --amend --no-edit -s" HEAD~2  # To sign last 2 commits
``

2022-09-16 04:25 UTC, mxgrey commented
It seems downstream packages are not happy with the transitive dependency:

```
   CMake Error at CMakeLists.txt:99 (add_executable):
    Target "rmf_task_dispatcher" links to target "Boost::filesystem" but the
    target was not found.  Perhaps a find_package() call is missing for an
    IMPORTED target, or an ALIAS target is missing?
```

Since websocketpp is an internal dependency it shouldn't need to be exposed in the public API, and I think it can be a private dependency. I'll give that a try and see if it works.

2022-09-16 10:00 UTC, mxgrey approved these changes

2022-09-16 10:01 UTC, mxgrey commented
I'm going to merge this PR since it has changes which are definitely valuable.  @orensbruli please let us know if the current state of this PR is able to work on Redhat yet.

2022-09-16 10:02 UTC, merged