Add support of fleet-level task
open-rmf/rmf_ros2 pull request #317
Opened 2024-01-10 14:15 UTC by cwrx777

Fleet-level task is implemented by ignoring `bid_notice` msg in `bid_notice_cb` if the `fleet_name` in the task_request does not match the fleet's name.

2024-01-11 02:43 UTC, Yadunund requested changes

2024-01-11 02:43 UTC, Yadunund commented on rmf_fleet_adapter/src/rmf_fleet_adapter/agv/FleetUpdateHandle.cpp
> +
Delete unnecessary new lines.

2024-01-11 02:43 UTC, Yadunund commented on rmf_fleet_adapter/src/rmf_fleet_adapter/agv/FleetUpdateHandle.cpp
> +
I think this block can be simplified a bit. Also add some comments and logs.
```suggestion
  //  If a fleet_name was specified in the request, only proceed if the value matches
  // the name of this fleet. 
  if (request_msg.contains("fleet_name") &&
    request_msg["fleet_name"].template get<std::string>() != name)
  {
    RCLCPP_INFO(
      node->get_logger(),
      "Ignoring BidNotice request as it is for fleet %s.,
      request_msg["fleet_name"].template get<std::string>().c_str());
    return;
  } 
```

2024-01-15 08:46 UTC, Yadunund commented on rmf_fleet_adapter/src/rmf_fleet_adapter/agv/FleetUpdateHandle.cpp
> +
@cwrx777 this is still unaddressed.

2024-01-16 01:45 UTC, cwrx777 commented on rmf_fleet_adapter/src/rmf_fleet_adapter/agv/FleetUpdateHandle.cpp
> +
@Yadunund 
Done. please revieew

2024-01-16 04:32 UTC, Yadunund approved these changes

2024-01-16 04:50 UTC, Yadunund requested changes
Looks like there are some whitespaces on line 506 which is making CI unhappy. Can you format the code? `ament_uncrustify -c ~/ws_rmf/src/rmf/rmf_utils/rmf_utils/test/format/rmf_code_style.cfg ~/ws_rmf/src/rmf/rmf_ros2/rmf_fleet_adapter/src/rmf_fleet_adapter/ --reformat
` should automatically format the code.

2024-01-16 07:34 UTC, Yadunund submitted a review, later dismissed

2024-01-16 12:06 UTC, Yadunund commented
@cwrx777 can you ensure all your commits are signed?

2024-01-19 02:51 UTC, Yadunund commented
@cwrx777 this merging is blocked by not having signed commits.

2024-01-26 06:36 UTC, Yadunund commented
@cwrx777 looks like something went wrong with the rebase and there are several new commits and diffs. Could you grant me push access to your fork/branch? I can clean this up and get it merged.

2024-01-26 06:48 UTC, cwrx777 commented
> @cwrx777 looks like something went wrong with the rebase and there are several new commits and diffs. Could you grant me push access to your fork/branch? I can clean this up and get it merged.

@Yadunund, I've granted you contributor access. Please try. Sorry for the trouble.

2024-01-26 07:14 UTC, Yadunund approved these changes

2024-01-26 07:45 UTC, merged