Add Backward-ROS for improved logging in event of segfaults
open-rmf/rmf_ros2 pull request #327
Opened 2024-02-22 02:48 UTC by arjo129

## New feature implementation

### Implemented feature

[`backward-ros`](https://github.com/pal-robotics/backward_ros/) provides a clean way to catch unhandled exceptions and segfaults and is able to print a stack trace when a program crashes. This PR adds `backward-ros` to rmf ros2 nodes so that we can trace causes for segfaults.

Note: This will only work for pure C++ nodes. If we want logging in downstream fleet adapters they will have to handle that themselves either using `backward-cpp` or `faulthandler` in python.

2024-03-01 03:39 UTC, Yadunund requested changes
Thanks for adding this functionality.

I'm not very familiar with `backward_ros/backward-cpp` and have the following questions:
* Is it used in any other large projects in the ROS/Gazebo ecosystem?
* Is there any additional overhead from its usage?
* Any stats on increase in compile times if any?
slightly concerned about the stability of the pkg since it is externally maintained. One nice thing is that it is released into Rolling from `ros2-gbp` so it should be available for each new ROS distro which is nice.

2024-03-01 03:39 UTC, Yadunund commented on rmf_fleet_adapter/package.xml
> +  <depend>backward_ros</depend>
Nit: Sort alphabetical for all package.xmls changed.

2024-03-06 02:46 UTC, arjo129 commented
> Is it used in any other large projects in the ROS/Gazebo ecosystem?

According to https://index.ros.org/p/backward_ros/#iron-deps seems like a lot of `ros2_controls` packages are using it.

> Is there any additional overhead from its usage?

My understanding is that no. This package simply installs a signal handler for `SIGSEGV`. The nice thing is that if we build with RelWithDebugInfo it should spit out the right stack trace thus speeding up debugging by a lot.

>Any stats on increase in compile times if any?

Nothing noticeable for me. I suspect a minor increase as we would have to link a new library in - but its not like we are linking templatized code.

2024-03-06 02:57 UTC, Yadunund commented
Thanks for the info. Sounds great to include! We can merge after addressing the sorting of dep pkgs.

2024-03-06 03:20 UTC, Yadunund approved these changes

2024-03-06 04:42 UTC, merged