Update _last_active_task_time if robot is executing task
open-rmf/rmf_ros2 pull request #384
Opened 2024-08-23 06:46 UTC by cwrx777

## Bug fix

### Fixed bug
Reference: open-rmf/rmf#516

### Fix applied
Set `_last_active_task_time` to `now` if the robot is currently doing task.

2024-08-25 04:34 UTC, Yadunund requested changes

2024-08-25 04:34 UTC, Yadunund commented on rmf_fleet_adapter/src/rmf_fleet_adapter/agv/RobotContext.cpp
> +
Nit: Unnecessary newline.
```suggestion
```

2024-08-25 04:34 UTC, Yadunund commented on rmf_fleet_adapter/src/rmf_fleet_adapter/agv/RobotContext.cpp
> +  else if (_last_active_task_time + dt < now)
Some style guides may complain if we have an `else if` block without an `else` so better if we can include something like.
```
else
{
  continue;
}

```

2024-09-09 16:31 UTC, Yadunund approved these changes
LGTM from me. Will wait for an approval from @mxgrey before merging.

2024-09-09 17:30 UTC, mxgrey approved these changes
Makes sense, thanks for the fix!

2024-09-09 17:31 UTC, merged